name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/bachgy/mototours-backend
            ghcr.io/bachgy/mototours-frontend

      - name: Build backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend/MotoTours.Api
          push: true
          tags: ghcr.io/bachgy/mototours-backend:latest

      - name: Build frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/bachgy/mototours-frontend:latest
